# --- General options --- #

remote_theme: daattali/beautiful-jekyll

baseurl: "secdev.github.io"

title: Scapy
description: Scapy - the Python-based interactive packet manipulation program & library.

# --- Navigation bar options --- #

navbar-links:
  Home: index
  Downloads: download/
  Documentation: http://scapy.readthedocs.io/
  Awesome Scapy: awesome-scapy/

avatar: "./assets/img/logo.png"
round-avatar: false

# --- Footer options --- #

author: Philippe Biondi and the Scapy community.
url-pretty: "scapy.net"

social-network-links:
  github: secdev

# Output options (more information on Jekyll's site)
timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - awesome-scapy/LICENSE.md
