using System;
using System.Linq;
using System.Text;
using MithrilShards.Chain.Bitcoin.Crypto; // Assuming RIPEMD160 is in this namespace
using Xunit;

namespace MithrilShards.Chain.BitcoinTests.Crypto
{
   public class RIPEMD160Tests
   {
      private string BytesToHex(byte[] bytes)
      {
         return BitConverter.ToString(bytes).Replace("-", "").ToLowerInvariant();
      }

      private byte[] HexToBytes(string hex)
      {
         return Enumerable.Range(0, hex.Length / 2)
                          .Select(x => Convert.ToByte(hex.Substring(x * 2, 2), 16))
                          .ToArray();
      }

      [Theory]
      [InlineData("", "9c1185a5c5e9fc54612808977ee8f548b2258d31")]
      [InlineData("a", "0bdc9d2d256b3ee9daae347be6f4dc835a467ffe")]
      [InlineData("abc", "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc")]
      [InlineData("message digest", "5d0689ef495000e47304056df63e81bd43bb5954")]
      [InlineData("abcdefghijklmnopqrstuvwxyz", "f71c27109c692c1b56bbdceb5b9d2865b3708dbc")]
      [InlineData("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", "b0e20b6e3116640286ed3a87a5713079b21f5189")]
      [InlineData("12345678901234567890123456789012345678901234567890123456789012345678901234567890", "9b752e463cfdd4d0adaf2e13463069a6cb6b253b")]
      public void RIPEMD160_KnownTestVectors_ComputesCorrectHash(string input, string expectedHexOutput)
      {
         // Arrange
         byte[] data = Encoding.ASCII.GetBytes(input);
         byte[] expectedOutput = HexToBytes(expectedHexOutput);

         // Act
         byte[] actualOutput = RIPEMD160.ComputeHash(data);

         // Assert
         // IMPORTANT NOTE: These tests WILL FAIL with the current SKELETON implementation of RIPEMD160.cs.
         // They are here to validate a fully implemented version.
         // To make them pass with the skeleton, you would need to compare against the placeholder output
         // generated by the skeleton, which is not the goal here. The goal is to test against official vectors.
         if (BytesToHex(actualOutput) != expectedHexOutput)
         {
             // This message will be helpful when running tests with the skeleton implementation.
             System.Diagnostics.Debug.WriteLine($"Test Vector Failed (as expected with skeleton): Input='{input}', Expected='{expectedHexOutput}', Got='{BytesToHex(actualOutput)}'");
         }
         Assert.Equal(expectedOutput, actualOutput);
      }

      [Fact]
      public void RIPEMD160_OutputIsAlways20Bytes()
      {
         // Arrange
         byte[] data1 = Encoding.ASCII.GetBytes("short");
         byte[] data2 = Encoding.ASCII.GetBytes("this is a much longer test string to ensure output size consistency");

         // Act
         byte[] output1 = RIPEMD160.ComputeHash(data1);
         byte[] output2 = RIPEMD160.ComputeHash(data2);

         // Assert
         Assert.Equal(RIPEMD160.HASH_BYTE_SIZE, output1.Length);
         Assert.Equal(RIPEMD160.HASH_BYTE_SIZE, output2.Length);
      }
   }
}
