using System;
using System.Globalization;
using System.Linq;
using System.Numerics; // For BigInteger if used for ScriptNum
using MithrilShards.Chain.Bitcoin.Protocol.Types; // For OpCodeType

namespace MithrilShards.Chain.Bitcoin.Consensus.Validation.Script
{
   /// <summary>
   /// Represents a single element in a Bitcoin script, which can be an opcode or a data push.
   /// </summary>
   public class ScriptElement
   {
      /// <summary>
      /// The opcode for this script element.
      /// If this element represents a data push, OpCode will be the specific OP_PUSHDATA instruction
      /// (e.g., OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, or a direct push for small data).
      /// For OP_0 to OP_16, it's the specific opcode.
      /// </summary>
      public OpCodeType OpCode { get; }

      /// <summary>
      /// The data being pushed onto the stack.
      /// Null if the OpCode is not a data push operation (e.g., OP_ADD, OP_VERIFY).
      /// For OP_0 (OP_FALSE), this is an empty byte array. For OP_1 to OP_16, this is a byte array representing the number.
      /// </summary>
      public byte[]? Data { get; }

      /// <summary>
      /// Initializes a new instance of the <see cref="ScriptElement"/> class for an opcode that is not a data push.
      /// </summary>
      /// <param name="opCode">The opcode.</param>
      public ScriptElement(OpCodeType opCode)
      {
         if (IsPushDataOpCode(opCode) && opCode > OpCodeType.OP_16 && opCode != OpCodeType.OP_RESERVED && opCode != OpCodeType.OP_1NEGATE) // OP_1NEGATE and OP_0-OP_16 push data
         {
            throw new ArgumentException("Opcode indicates a data push, but no data was provided. Use the constructor with data parameter.", nameof(opCode));
         }
         OpCode = opCode;
         Data = OpCode switch
         {
            OpCodeType.OP_0 or OpCodeType.OP_FALSE => System.Array.Empty<byte>(),
            OpCodeType.OP_1NEGATE => new byte[] { 0x81 }, // -1
            >= OpCodeType.OP_1 and <= OpCodeType.OP_16 => new byte[] { (byte)(opCode - OpCodeType.OP_0) },
            _ => null
         };
      }

      /// <summary>
      /// Initializes a new instance of the <see cref="ScriptElement"/> class for a data push operation.
      /// </summary>
      /// <param name="opCode">The data push opcode (e.g., OP_PUSHDATA1, or the length of data for direct pushes).</param>
      /// <param name="data">The data to be pushed.</param>
      public ScriptElement(OpCodeType opCode, byte[] data)
      {
         if (data == null)
         {
            throw new ArgumentNullException(nameof(data));
         }

         if (!IsPushDataOpCode(opCode) && !(opCode >= 0 && (int)opCode <= (int)OpCodeType.OP_PUSHDATA4)) // direct push ops are 0x01-0x4b
         {
             // Allow OP_0 to OP_16 and OP_1NEGATE to be constructed this way if data matches their canonical form
             bool isSpecialPush = opCode == OpCodeType.OP_0 && data.Length == 0 ||
                                 opCode == OpCodeType.OP_1NEGATE && data.SequenceEqual(new byte[] { 0x81 }) ||
                                 (opCode >= OpCodeType.OP_1 && opCode <= OpCodeType.OP_16 && data.Length == 1 && data[0] == (opCode - OpCodeType.OP_0));
             if (!isSpecialPush)
             {
                 throw new ArgumentException("Opcode does not indicate a data push operation, or data is inconsistent with special opcode.", nameof(opCode));
             }
         }

         OpCode = opCode;
         Data = data;
      }

      /// <summary>
      /// Returns true if this script element represents a data push operation.
      /// This includes OP_0 through OP_16, OP_1NEGATE, and OP_PUSHDATA variants.
      /// </summary>
      public bool IsPushData()
      {
         if (Data != null) return true; // If data is present, it's a push
         // Opcodes OP_0-OP_16 and OP_1NEGATE are considered pushes even if Data might be generated by constructor.
         return (OpCode >= OpCodeType.OP_0 && OpCode <= OpCodeType.OP_16) || OpCode == OpCodeType.OP_1NEGATE;
      }

      /// <summary>
      /// Helper to determine if an OpCodeType is inherently a data-pushing opcode,
      /// either a direct length push (0x01-0x4b), OP_PUSHDATA1/2/4, or special small integers.
      /// </summary>
      public static bool IsPushDataOpCode(OpCodeType opCode)
      {
         return (opCode >= 0 && (int)opCode <= (int)OpCodeType.OP_PUSHDATA4) || // Includes direct pushes 0x01-0x4b, and OP_PUSHDATA1/2/4
                (opCode >= OpCodeType.OP_0 && opCode <= OpCodeType.OP_16) ||
                opCode == OpCodeType.OP_1NEGATE;
      }


      /// <summary>
      /// Gets the data as a CScriptNum (Bitcoin's way of representing numbers in scripts).
      /// Throws if this element is not a data push or if data is not a valid ScriptNum.
      /// </summary>
      /// <param name="requireMinimal">If true, ensures the number is minimally encoded.</param>
      /// <param name="maxLength">Maximum length of the byte array representing the number.</param>
      /// <returns>The ScriptNum representation.</returns>
      public ScriptNum GetScriptNum(bool requireMinimal, int maxLength = ScriptNum.MAXIMUM_ELEMENT_SIZE)
      {
         if (Data == null)
         {
            // OP_0 to OP_16 and OP_1NEGATE have Data generated by constructor.
            // Other opcodes that don't push data will have Data == null.
            if (OpCode >= OpCodeType.OP_0 && OpCode <= OpCodeType.OP_16)
            {
               return new ScriptNum(OpCode - OpCodeType.OP_0);
            }
            if (OpCode == OpCodeType.OP_1NEGATE)
            {
               return new ScriptNum(-1);
            }
            throw new InvalidOperationException("Cannot get ScriptNum from an element that is not a data push.");
         }
         return new ScriptNum(Data, requireMinimal, maxLength);
      }

      public override string ToString()
      {
         if (OpCode >= OpCodeType.OP_0 && OpCode <= OpCodeType.OP_PUSHDATA4 && Data != null)
         {
            // For data pushes, show data length or a snippet
            return $"PUSH({Data.Length}): {BitConverter.ToString(Data.Take(20).ToArray()).Replace("-", "")}{(Data.Length > 20 ? "..." : "")}";
         }
         return OpCode.ToString();
      }
   }
}
